### ISSUE TITLE
Defaults conda channel in linux.yml

### ISSUE THREAD

**Issue by jjv5** [SBQ-1999/CryFold#1]
Anaconda requires a license to use the 'defaults' conda channel for any institution with more than 200 people. We avoid using defaults in any software. 

Would it be possible to reedo the yaml file to use conda-forge instead?

**Comment by SBQ-1999** [comment]
Hi,

Thank you very much for your suggestion! We will remove 'defaults' as a conda channel in the next version.

Best regards,
Baoquan.
